#pragma once
#pragma comment(lib, "msimg32.lib")
#include<Windows.h>
#include<string>
#include<vector>
using namespace std;

#define CHESSBOARDDRAWSTARTPOSX 0
#define CHESSBOARDDRAWSTARTPOSY 0
#define CHESSBOARDWIDTH 8
#define CHESSBOARDHEIGHT 8
#define CHESSBOARDBLOCKSIZE 50
#define CHESSPIECESIZE 50
#define CHESSPIECEMOVESPEED 10
#define DRAWFLAGMAX 50

enum GAMESTATE
{
	GAMESTATE_GAMEOVER = 999,
	GAMESTATE_WHITE_THINKING = 990,
	GAMESTATE_WHITE_MOVEPHASE,
	GAMESTATE_BLACK_THINKING,
	GAMESTATE_BLACK_MOVEPHASE,
	GAMESTATE_WHITE_PROMOTION,
	GAMESTATE_BLACK_PROMOTION,
	GAMESTATE_WHITE_CHECK,
	GAMESTATE_BLACK_CHECK
};

enum CHESSPIECE
{
	CHESSPIECE_PAWN,
	CHESSPIECE_KNIGHT,
	CHESSPIECE_BISHOP,
	CHESSPIECE_ROOK,
	CHESSPIECE_QUEEN,
	CHESSPIECE_KING
};

enum CHESSPIECECOLOR
{
	CHESSPIECECOLOR_WHITE,
	CHESSPIECECOLOR_BLACK
};

enum CHESSPIECENUM
{
	CHESSPIECENUM_PAWN = 8,
	CHESSPIECENUM_KNIGHT = 2,
	CHESSPIECENUM_BISHOP = 2,
	CHESSPIECENUM_ROOK = 2,
	CHESSPIECENUM_QUEEN = 1,
	CHESSPIECENUM_KING = 1
};

enum BLOCKCOLOR
{
	BLOCKCOLOR_WHITE,
	BLOCKCOLOR_BLACK,
	BLOCKCOLOR_MAKER
};
